
import React, { useEffect, useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { supabase, isConfigured, setupSupabase } from '../lib/supabaseClient';
import { Job, Order, OrderStatus } from '../types';
import { IconCheck, IconX, IconArrowLeft } from '../components/Icons';

const SETUP_SQL = `
-- 1. Create Jobs Table (Updated with frequency)
create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  grade text,
  subject text,
  price text,
  frequency integer default 1,  -- New Field
  address text,
  contact_name text,
  contact_phone text,
  is_active boolean default true,
  status text default 'pending'
);

-- For existing tables, run this separately to add the column:
-- alter table public.jobs add column if not exists frequency integer default 1;

-- 2. Create Orders Table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  job_id bigint references public.jobs(id),
  student_contact text,
  status text default 'pending'
);

-- 3. Create Profiles Table
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  phone text unique not null,
  name text,
  school text,
  major text,
  grade text,
  experience text
);

-- 4. Enable Realtime
alter publication supabase_realtime add table orders;
`;

export const AdminDashboard: React.FC = () => {
  const [orders, setOrders] = useState<(Order & { jobs: Job })[]>([]);
  const [loading, setLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [configured, setConfigured] = useState(false);
  
  // Config state
  const [configUrl, setConfigUrl] = useState('');
  const [configKey, setConfigKey] = useState('');

  // Job Creation State
  const [newJob, setNewJob] = useState({
    grade: '',
    subject: '',
    title: '',
    price: '',
    frequency: 1,
    address: '',
    contact_name: '管理员',
    contact_phone: ''
  });

  useEffect(() => {
    setConfigUrl(localStorage.getItem('VITE_SUPABASE_URL') || '');
    setConfigKey(localStorage.getItem('VITE_SUPABASE_ANON_KEY') || '');
    setConfigured(isConfigured());
  }, []);

  const fetchPendingOrders = useCallback(async (isBackground = false) => {
    if (!isConfigured()) {
      setLoading(false);
      return;
    }
    
    if (!isBackground) setLoading(true);
    setErrorMsg(null);
    try {
      const { data, error } = await supabase
        .from('orders')
        .select('*, jobs(*)')
        .eq('status', OrderStatus.PENDING)
        .order('created_at', { ascending: true });

      if (error) {
        console.error("Error fetching orders:", error.message);
        setErrorMsg(error.message);
      } else {
        setOrders(data as any || []);
      }
    } catch (err: any) {
        console.error("Network error fetching orders:", err);
        setErrorMsg(err.message || "Failed to fetch orders");
    }
    
    if (!isBackground) setLoading(false);
  }, []);

  const handleSaveConfig = () => {
    const url = configUrl.trim();
    const key = configKey.trim();

    if (!url || !key) return alert("请输入 URL 和 Key");

    try {
      new URL(url);
    } catch (e) {
      return alert("URL 格式无效。请输入以 https:// 开头的有效地址");
    }

    setupSupabase(url, key);
    setConfigured(true);
    fetchPendingOrders();
  };

  // Initial Load & Realtime
  useEffect(() => {
    if (configured) {
        fetchPendingOrders();

        const channel = supabase
          .channel('admin_dashboard_realtime')
          .on(
            'postgres_changes',
            { event: '*', schema: 'public', table: 'orders' },
            (payload) => {
              console.log('Admin Dashboard: Realtime update', payload);
              fetchPendingOrders(true);
            }
          )
          .subscribe();

        return () => {
          supabase.removeChannel(channel);
        };
    }
  }, [configured, fetchPendingOrders]);

  const handleUpdateStatus = async (orderId: number, status: OrderStatus) => {
    // Optimistic Update
    setOrders(prev => prev.filter(o => o.id !== orderId));

    const { error } = await supabase
      .from('orders')
      .update({ status })
      .eq('id', orderId);

    if (error) {
      alert("更新失败: " + error.message);
      fetchPendingOrders(true); // Revert
    }
  };

  const handleCreateJob = async () => {
    // Basic validation
    if (!newJob.title || !newJob.contact_phone) {
        return alert("请至少填写职位标题和联系电话");
    }

    const { error } = await supabase.from('jobs').insert([{
      title: newJob.title,
      grade: newJob.grade,
      subject: newJob.subject,
      price: newJob.price,
      frequency: newJob.frequency,
      address: newJob.address,
      contact_name: newJob.contact_name,
      contact_phone: newJob.contact_phone,
      is_active: true,
      status: 'published'
    }]);

    if (error) alert("创建失败: " + error.message);
    else {
      alert("需求发布成功！");
      setNewJob({
        grade: '', subject: '', title: '', price: '', frequency: 1, address: '', contact_name: '管理员', contact_phone: ''
      });
    }
  };

  const showConfigForm = !configured || (errorMsg && !errorMsg.includes('Could not find the table') && !errorMsg.includes('does not exist'));
  const isMissingTables = errorMsg && (errorMsg.includes('Could not find the table') || errorMsg.includes('does not exist'));

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      <div className="max-w-4xl mx-auto space-y-8">
        
        {/* Navigation Header */}
        <div className="flex items-center gap-4">
           <Link to="/" className="inline-flex items-center gap-2 text-gray-600 hover:text-gray-900 transition-colors font-medium">
             <IconArrowLeft className="w-5 h-5" />
             返回首页
           </Link>
           <h1 className="text-xl text-gray-400">|</h1>
           <h1 className="text-xl font-bold text-gray-800">后台管理看板</h1>
           <div className="ml-auto flex items-center gap-2 px-3 py-1 bg-white rounded-full text-xs text-gray-500 shadow-sm border border-gray-100">
               <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
               </span>
               数据实时同步中
           </div>
        </div>

        {/* Section 1: Pending Orders / Errors */}
        <section className="bg-white rounded-xl shadow p-6">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-bold text-gray-800">待审核订单</h2>
            <button onClick={() => fetchPendingOrders()} className="text-blue-600 text-sm hover:underline">刷新</button>
          </div>
          
          {showConfigForm && (
             <div className="mb-6 bg-red-50 text-red-700 p-4 rounded-lg border border-red-200">
               <p className="font-bold mb-2">
                 {!configured ? '需要配置 Supabase' : `错误: ${errorMsg}`}
               </p>
               <div className="bg-white p-3 rounded border border-red-100 mt-2">
                 <p className="text-xs text-gray-500 mb-2">Supabase 凭据</p>
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                    <input 
                      className="border p-2 rounded text-sm" 
                      placeholder="Supabase URL" 
                      value={configUrl} 
                      onChange={e => setConfigUrl(e.target.value)} 
                    />
                    <input 
                      className="border p-2 rounded text-sm" 
                      type="password" 
                      placeholder="Anon Key" 
                      value={configKey} 
                      onChange={e => setConfigKey(e.target.value)} 
                    />
                 </div>
                 <button onClick={handleSaveConfig} className="mt-2 text-xs bg-red-600 text-white px-3 py-1 rounded">保存并重试</button>
               </div>
             </div>
          )}

          {isMissingTables && (
            <div className="mb-6 bg-yellow-50 text-yellow-800 p-6 rounded-lg border border-yellow-200">
              <h3 className="font-bold text-lg mb-2">数据库未初始化或需要升级</h3>
              <p className="mb-4">请在 Supabase 中运行以下 SQL 以创建或更新表结构。</p>
              
              <div className="bg-gray-800 text-gray-100 p-4 rounded-lg overflow-x-auto text-sm font-mono relative">
                 <pre>{SETUP_SQL}</pre>
                 <button 
                   onClick={() => navigator.clipboard.writeText(SETUP_SQL)}
                   className="absolute top-2 right-2 bg-gray-600 hover:bg-gray-500 text-xs px-2 py-1 rounded"
                 >
                   复制 SQL
                 </button>
              </div>
            </div>
          )}

          {configured && loading ? (
            <p>加载中...</p>
          ) : configured && !isMissingTables && orders.length === 0 && !errorMsg ? (
            <p className="text-gray-500 italic">暂无待审核订单。</p>
          ) : configured && !isMissingTables && !errorMsg && (
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead>
                  <tr className="border-b border-gray-200 text-gray-500 text-sm">
                    <th className="pb-3">学生联系方式</th>
                    <th className="pb-3">职位标题</th>
                    <th className="pb-3 text-right">操作</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {orders.map(order => (
                    <tr key={order.id} className="group hover:bg-gray-50">
                      <td className="py-4 font-mono text-sm">{order.student_contact}</td>
                      <td className="py-4 text-sm font-medium">
                        {order.jobs?.title || `职位 #${order.job_id}`}<br/>
                        <span className="text-xs text-gray-400">
                            频率: 每周{order.jobs?.frequency || 1}次 ({order.jobs?.grade})
                        </span>
                      </td>
                      <td className="py-4 text-right space-x-2">
                        <button 
                          onClick={() => handleUpdateStatus(order.id, OrderStatus.APPROVED)}
                          className="inline-flex items-center px-3 py-1.5 bg-green-100 text-green-700 rounded-md hover:bg-green-200 transition-colors text-sm font-medium"
                        >
                          <IconCheck className="w-4 h-4 mr-1" /> 通过
                        </button>
                        <button 
                          onClick={() => handleUpdateStatus(order.id, OrderStatus.REJECTED)}
                          className="inline-flex items-center px-3 py-1.5 bg-red-100 text-red-700 rounded-md hover:bg-red-200 transition-colors text-sm font-medium"
                        >
                          <IconX className="w-4 h-4 mr-1" /> 拒绝
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </section>

        {/* Section 2: Create New Job (Manual) */}
        {!isMissingTables && (
        <section className="bg-white rounded-xl shadow p-6 border border-gray-100">
           <h2 className="text-xl font-bold text-gray-800 mb-6">
             发布新需求
           </h2>
           
           <div className="space-y-4">
             {/* Row 1 */}
             <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">年级</label>
                  <input className="w-full border p-2 rounded" placeholder="如: 高一" value={newJob.grade} onChange={e => setNewJob({...newJob, grade: e.target.value})} />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">科目</label>
                  <input className="w-full border p-2 rounded" placeholder="如: 数学" value={newJob.subject} onChange={e => setNewJob({...newJob, subject: e.target.value})} />
                </div>
             </div>

             {/* Row 2 */}
             <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">职位标题 (展示给学生看)</label>
                <input className="w-full border p-2 rounded font-medium" placeholder="如: 高一数学辅导，周末上课" value={newJob.title} onChange={e => setNewJob({...newJob, title: e.target.value})} />
             </div>

             {/* Row 3 */}
             <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
               <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">每周次数</label>
                  <select 
                     className="w-full border p-2 rounded bg-white" 
                     value={newJob.frequency} 
                     onChange={e => setNewJob({...newJob, frequency: parseInt(e.target.value)})}
                  >
                     {[1,2,3,4,5,6,7].map(n => <option key={n} value={n}>每周{n}次</option>)}
                  </select>
               </div>
               <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">价格建议</label>
                  <input className="w-full border p-2 rounded" placeholder="如: 150" value={newJob.price} onChange={e => setNewJob({...newJob, price: e.target.value})} />
               </div>
               <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">地址/区域</label>
                  <input className="w-full border p-2 rounded" placeholder="如: 朝阳区大悦城" value={newJob.address} onChange={e => setNewJob({...newJob, address: e.target.value})} />
               </div>
             </div>

             {/* Row 4 */}
             <div className="grid grid-cols-1 md:grid-cols-2 gap-4 bg-gray-50 p-4 rounded-lg border border-gray-100">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">联系人</label>
                  <input className="w-full border p-2 rounded" placeholder="如: 王老师" value={newJob.contact_name} onChange={e => setNewJob({...newJob, contact_name: e.target.value})} />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">联系电话 (学生付费后可见)</label>
                  <input className="w-full border p-2 rounded" placeholder="如: 13800138000" value={newJob.contact_phone} onChange={e => setNewJob({...newJob, contact_phone: e.target.value})} />
                </div>
             </div>
             
             <button onClick={handleCreateJob} className="w-full bg-black text-white py-3 rounded-lg hover:bg-gray-800 transition-colors font-semibold mt-2">
               立即发布
             </button>
           </div>
        </section>
        )}

      </div>
    </div>
  );
};
