
import React, { useEffect, useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { supabase, isConfigured, setupSupabase } from '../lib/supabaseClient';
import { Job, Order, OrderStatus } from '../types';
import { IconCheck, IconX, IconArrowLeft, IconLock, IconUnlock, IconTrash } from '../components/Icons';

const INIT_SQL = `
-- 【说明】无需因为 'taken' 状态修改 SQL。status 字段是 text 类型，可以直接存储新状态。

-- 1. Create Jobs Table
create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  grade text,
  subject text,
  price text,
  frequency integer default 1,
  address text,
  contact_name text,
  contact_phone text,
  is_active boolean default true,
  status text default 'pending'
);

-- 2. Create Orders Table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  job_id bigint references public.jobs(id),
  student_contact text,
  status text default 'pending'
);

-- 3. Create Profiles Table
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  phone text unique not null,
  password text, 
  name text,
  school text,
  major text,
  grade text,
  experience text,
  preferred_grades text,
  preferred_subjects text
);

-- 4. Enable Realtime
alter publication supabase_realtime add table orders;
`;

const MIGRATION_SQL = `
-- 【数据库升级】仅运行一次 (如果你之前的 jobs 表没有 frequency 字段)
alter table public.jobs add column if not exists frequency integer default 1;

-- 【数据库升级 V2】添加偏好设置字段 (运行一次)
alter table public.profiles add column if not exists preferred_grades text;
alter table public.profiles add column if not exists preferred_subjects text;

-- 【数据库升级 V3】添加密码字段 (运行一次)
alter table public.profiles add column if not exists password text;
`;

type Tab = 'applications' | 'finance';

export const AdminDashboard: React.FC = () => {
  const [orders, setOrders] = useState<(Order & { jobs: Job })[]>([]);
  const [loading, setLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [configured, setConfigured] = useState(false);
  const [showSql, setShowSql] = useState(false);
  
  const [activeTab, setActiveTab] = useState<Tab>('applications');
  
  // Config state
  const [configUrl, setConfigUrl] = useState('');
  const [configKey, setConfigKey] = useState('');

  // Job Creation State
  const [newJob, setNewJob] = useState({
    grade: '',
    subject: '',
    title: '',
    price: '',
    frequency: 1,
    address: '',
    contact_name: '管理员',
    contact_phone: ''
  });

  useEffect(() => {
    setConfigUrl(localStorage.getItem('VITE_SUPABASE_URL') || '');
    setConfigKey(localStorage.getItem('VITE_SUPABASE_ANON_KEY') || '');
    setConfigured(isConfigured());
  }, []);

  const fetchOrders = useCallback(async (isBackground = false) => {
    if (!isConfigured()) {
      setLoading(false);
      return;
    }
    
    if (!isBackground) setLoading(true);
    setErrorMsg(null);
    try {
      // Fetch based on Tab
      let statusFilter: OrderStatus[] = [];
      if (activeTab === 'applications') {
          statusFilter = [OrderStatus.APPLYING, OrderStatus.PARENT_APPROVED];
      } else {
          statusFilter = [OrderStatus.PAYMENT_PENDING, OrderStatus.FINAL_APPROVED];
      }

      const { data, error } = await supabase
        .from('orders')
        .select('*, jobs(*)')
        .in('status', statusFilter)
        .order('created_at', { ascending: false });

      if (error) {
        console.error("Error fetching orders:", error.message);
        setErrorMsg(error.message);
      } else {
        setOrders(data as any || []);
      }
    } catch (err: any) {
        console.error("Network error fetching orders:", err);
        setErrorMsg(err.message || "Failed to fetch orders");
    }
    
    if (!isBackground) setLoading(false);
  }, [activeTab]);

  const handleSaveConfig = () => {
    const url = configUrl.trim();
    const key = configKey.trim();

    if (!url || !key) return alert("请输入 URL 和 Key");

    try {
      new URL(url);
    } catch (e) {
      return alert("URL 格式无效。请输入以 https:// 开头的有效地址");
    }

    setupSupabase(url, key);
    setConfigured(true);
    fetchOrders();
  };

  // Initial Load & Realtime
  useEffect(() => {
    if (configured) {
        fetchOrders();

        const channel = supabase
          .channel('admin_dashboard_realtime')
          .on(
            'postgres_changes',
            { event: '*', schema: 'public', table: 'orders' },
            (payload) => {
              console.log('Realtime update', payload);
              fetchOrders(true);
            }
          )
          .subscribe();

        return () => {
          supabase.removeChannel(channel);
        };
    }
  }, [configured, fetchOrders]);

  // Actions
  const handleUpdateStatus = async (orderId: number, status: OrderStatus) => {
    // Optimistic UI
    setOrders(prev => prev.map(o => o.id === orderId ? { ...o, status } : o));

    const { error } = await supabase
      .from('orders')
      .update({ status })
      .eq('id', orderId);

    if (error) {
      alert("更新失败: " + error.message);
      fetchOrders(true); 
    }
  };

  const handleConfirmPayment = async (orderId: number, jobId: number) => {
      if(!confirm("确认收款？这将把职位标记为'已接单'并下架。")) return;

      const { error: err1 } = await supabase.from('orders').update({ status: OrderStatus.FINAL_APPROVED }).eq('id', orderId);
      if (err1) return alert("订单更新失败");

      const { error: err2 } = await supabase.from('jobs').update({ status: 'taken' }).eq('id', jobId);
      if (err2) return alert("职位下架失败");

      alert("操作成功");
      fetchOrders(true);
  };

  const handleRelistJob = async (jobId: number) => {
      if(!confirm("确认重新上架？这将允许新学生申请。")) return;
      await supabase.from('jobs').update({ status: 'published' }).eq('id', jobId);
      alert("已重新上架！");
  };

  const handleDeleteJob = async (jobId: number) => {
      if(!confirm("⚠️ 危险操作：确定要彻底删除这个帖子吗？\n\n注意：相关的订单记录也会被一并删除！")) return;
      
      // 1. Delete associated orders first to avoid Foreign Key errors
      await supabase.from('orders').delete().eq('job_id', jobId);
      
      // 2. Delete the job
      const { error } = await supabase.from('jobs').delete().eq('id', jobId);
      
      if(error) {
          alert("删除失败: " + error.message);
      } else {
          alert("删除成功");
          fetchOrders(true);
      }
  };

  const handleCreateJob = async () => {
    if (!newJob.title || !newJob.contact_phone) {
        return alert("请至少填写职位标题和联系电话");
    }

    const { error } = await supabase.from('jobs').insert([{
      title: newJob.title,
      grade: newJob.grade,
      subject: newJob.subject,
      price: newJob.price,
      frequency: newJob.frequency,
      address: newJob.address,
      contact_name: newJob.contact_name,
      contact_phone: newJob.contact_phone,
      is_active: true,
      status: 'published'
    }]);

    if (error) {
        if (error.message?.includes('frequency')) {
            alert("发布失败：数据库缺少 frequency 字段。\n请点击下方的 '数据库维护命令' 并运行升级 SQL。");
        } else {
            alert("创建失败: " + error.message);
        }
    } else {
      alert("需求发布成功！");
      setNewJob({
        grade: '', subject: '', title: '', price: '', frequency: 1, address: '', contact_name: '管理员', contact_phone: ''
      });
    }
  };

  const showConfigForm = !configured || (errorMsg && !errorMsg.includes('Could not find the table') && !errorMsg.includes('does not exist'));
  const isMissingTables = errorMsg && (errorMsg.includes('Could not find the table') || errorMsg.includes('does not exist'));

  // Grouping Logic
  const groupedOrders: Record<number, (Order & { jobs: Job })[]> = {};
  orders.forEach(o => {
    if (!groupedOrders[o.job_id]) groupedOrders[o.job_id] = [];
    groupedOrders[o.job_id].push(o);
  });

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      <div className="max-w-5xl mx-auto space-y-8">
        
        {/* Navigation Header */}
        <div className="flex items-center gap-4">
           <Link to="/" className="inline-flex items-center gap-2 text-gray-600 hover:text-gray-900 transition-colors font-medium">
             <IconArrowLeft className="w-5 h-5" />
             返回首页
           </Link>
           <h1 className="text-xl text-gray-400">|</h1>
           <h1 className="text-xl font-bold text-gray-800">后台管理看板</h1>
           <div className="ml-auto flex items-center gap-2 px-3 py-1 bg-white rounded-full text-xs text-gray-500 shadow-sm border border-gray-100">
               <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
               </span>
               数据实时同步中
           </div>
        </div>

        {/* Section 1: Orders Management */}
        <section className="bg-white rounded-xl shadow border border-gray-200 overflow-hidden">
          {/* Tabs */}
          <div className="flex border-b border-gray-200">
              <button 
                onClick={() => setActiveTab('applications')}
                className={`flex-1 py-4 text-sm font-bold text-center transition-colors ${activeTab === 'applications' ? 'bg-white text-blue-600 border-b-2 border-blue-600' : 'bg-gray-50 text-gray-500 hover:bg-gray-100'}`}
              >
                1. 申请管理 ({activeTab === 'applications' ? Object.keys(groupedOrders).length : '...'})
              </button>
              <button 
                onClick={() => setActiveTab('finance')}
                className={`flex-1 py-4 text-sm font-bold text-center transition-colors ${activeTab === 'finance' ? 'bg-white text-green-600 border-b-2 border-green-600' : 'bg-gray-50 text-gray-500 hover:bg-gray-100'}`}
              >
                2. 财务与完结 ({activeTab === 'finance' ? orders.length : '...'})
              </button>
          </div>

          <div className="p-6">
            <div className="flex justify-between items-center mb-6">
                <h2 className="text-lg font-bold text-gray-800">
                    {activeTab === 'applications' ? '待接单申请 (按职位分组)' : '待确认收款 / 历史订单'}
                </h2>
                <button onClick={() => fetchOrders()} className="text-blue-600 text-sm hover:underline">刷新列表</button>
            </div>
          
            {showConfigForm && (
                <div className="mb-6 bg-red-50 text-red-700 p-4 rounded-lg border border-red-200">
                {/* ... Config Form (Shortened for brevity as it's same logic) ... */}
                <p className="font-bold mb-2">{!configured ? '需要配置 Supabase' : `错误: ${errorMsg}`}</p>
                <button onClick={handleSaveConfig} className="text-xs bg-red-600 text-white px-3 py-1 rounded">重试连接</button>
                </div>
            )}

            {isMissingTables && (
                <div className="mb-6 bg-yellow-50 text-yellow-800 p-6 rounded-lg border border-yellow-200">
                <h3 className="font-bold text-lg mb-2">数据库未初始化</h3>
                <div className="bg-gray-800 text-gray-100 p-4 rounded-lg overflow-x-auto text-sm font-mono relative">
                    <pre>{INIT_SQL}</pre>
                    <button onClick={() => navigator.clipboard.writeText(INIT_SQL)} className="absolute top-2 right-2 bg-gray-600 text-xs px-2 py-1 rounded">复制</button>
                </div>
                </div>
            )}

            {/* Content Area */}
            {configured && !isMissingTables && !errorMsg && (
                <div className="space-y-6">
                {activeTab === 'applications' && Object.keys(groupedOrders).length === 0 && <p className="text-gray-400 text-center py-10">暂无申请</p>}
                {activeTab === 'finance' && orders.length === 0 && <p className="text-gray-400 text-center py-10">暂无收款记录</p>}

                {/* --- TAB 1: APPLICATIONS (GROUPED) --- */}
                {activeTab === 'applications' && Object.values(groupedOrders).map(group => {
                    const job = group[0].jobs;
                    return (
                        <div key={job.id} className="border border-gray-200 rounded-lg overflow-hidden shadow-sm">
                            <div className="bg-blue-50/50 px-4 py-3 border-b border-gray-200 flex justify-between items-center">
                                <div>
                                    <div className="font-bold text-gray-800 text-lg">{job.title}</div>
                                    <div className="text-xs text-gray-500 mt-1">
                                        价格: {job.price} | 频率: 每周{job.frequency}次 | 家长: {job.contact_name}
                                    </div>
                                </div>
                                <div className="flex items-center gap-3">
                                    <span className="bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded-full font-bold">
                                        {group.length} 位申请人
                                    </span>
                                    <button onClick={() => handleDeleteJob(job.id)} className="text-gray-400 hover:text-red-600 p-1">
                                        <IconTrash className="w-4 h-4" />
                                    </button>
                                </div>
                            </div>
                            <div className="divide-y divide-gray-100">
                                {group.map(order => (
                                    <div key={order.id} className="px-4 py-4 flex items-center justify-between hover:bg-gray-50 transition-colors">
                                        <div className="flex-1">
                                            <div className="flex items-center gap-2">
                                                <span className="font-mono text-sm font-bold text-gray-900">{order.student_contact}</span>
                                                {order.status === OrderStatus.PARENT_APPROVED && (
                                                    <span className="text-[10px] bg-green-100 text-green-700 px-2 py-0.5 rounded-full font-bold">已通过初审</span>
                                                )}
                                            </div>
                                            <div className="text-xs text-gray-400 mt-1">申请时间: {new Date(order.created_at).toLocaleString()}</div>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <button 
                                                onClick={() => handleUpdateStatus(order.id, OrderStatus.REJECTED)}
                                                className="px-3 py-1.5 text-xs font-bold text-red-600 bg-red-50 hover:bg-red-100 rounded border border-red-100"
                                            >
                                                拒绝
                                            </button>
                                            {order.status === OrderStatus.APPLYING ? (
                                                <button 
                                                    onClick={() => handleUpdateStatus(order.id, OrderStatus.PARENT_APPROVED)}
                                                    className="px-3 py-1.5 text-xs font-bold text-white bg-black hover:bg-gray-800 rounded shadow-sm"
                                                >
                                                    通过初审 (允许支付)
                                                </button>
                                            ) : (
                                                <span className="px-3 py-1.5 text-xs font-bold text-gray-400 bg-gray-100 rounded cursor-not-allowed">
                                                    等待学生支付...
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )
                })}

                {/* --- TAB 2: FINANCE --- */}
                {activeTab === 'finance' && orders.map(order => (
                    <div key={order.id} className={`flex flex-col md:flex-row md:items-center justify-between p-4 rounded-lg border ${order.status === OrderStatus.FINAL_APPROVED ? 'border-green-200 bg-green-50/30' : 'border-orange-200 bg-orange-50/30'}`}>
                        <div className="mb-4 md:mb-0">
                            <div className="flex items-center gap-2 mb-1">
                                <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${order.status === OrderStatus.FINAL_APPROVED ? 'bg-green-100 text-green-700' : 'bg-orange-100 text-orange-700'}`}>
                                    {order.status === OrderStatus.FINAL_APPROVED ? '已接单 (完成)' : '待确认收款'}
                                </span>
                                <span className="text-xs text-gray-400">订单 #{order.id}</span>
                            </div>
                            <div className="font-bold text-gray-800">{order.jobs?.title}</div>
                            <div className="text-sm text-gray-600 mt-1">学生: {order.student_contact}</div>
                            <div className="text-xs text-gray-400 mt-1">金额参考: {order.jobs?.price} (每周{order.jobs?.frequency}次)</div>
                        </div>

                        <div className="flex gap-2">
                             {order.status === OrderStatus.PAYMENT_PENDING ? (
                                 <>
                                    <button 
                                        onClick={() => handleUpdateStatus(order.id, OrderStatus.REJECTED)}
                                        className="px-4 py-2 text-sm font-bold text-red-600 bg-white border border-red-200 rounded hover:bg-red-50"
                                    >
                                        驳回
                                    </button>
                                    <button 
                                        onClick={() => handleConfirmPayment(order.id, order.job_id)}
                                        className="px-4 py-2 text-sm font-bold text-white bg-green-600 rounded shadow-sm hover:bg-green-700"
                                    >
                                        确认收款并放号
                                    </button>
                                 </>
                             ) : (
                                 <div className="flex items-center gap-2">
                                     <button 
                                         onClick={() => handleRelistJob(order.job_id)}
                                         className="px-3 py-1.5 text-xs font-bold text-gray-600 bg-white border border-gray-300 rounded hover:bg-gray-50"
                                     >
                                         重新上架职位
                                     </button>
                                     <button 
                                         onClick={() => handleDeleteJob(order.job_id)}
                                         className="px-3 py-1.5 text-xs font-bold text-red-500 flex items-center gap-1 hover:text-red-700"
                                     >
                                         <IconTrash className="w-3 h-3" /> 删除
                                     </button>
                                 </div>
                             )}
                        </div>
                    </div>
                ))}
                </div>
            )}
          </div>
          
          {/* SQL Helper (Optional) */}
          {configured && (
            <div className="bg-gray-50 p-2 text-center border-t border-gray-200">
                <button onClick={() => setShowSql(!showSql)} className="text-xs text-gray-400 hover:text-gray-600 underline">
                    {showSql ? '隐藏数据库维护命令' : '数据库维护命令'}
                </button>
                {showSql && (
                    <div className="mt-2 p-4 text-left max-w-2xl mx-auto">
                        <p className="text-xs font-bold mb-1">升级字段 (运行一次即可):</p>
                        <pre className="bg-gray-800 text-white p-2 rounded text-[10px] overflow-auto">{MIGRATION_SQL}</pre>
                    </div>
                )}
            </div>
          )}
        </section>

        {/* Section 2: Create New Job (Manual) */}
        {!isMissingTables && (
        <section className="bg-white rounded-xl shadow p-6 border border-gray-200">
           <h2 className="text-lg font-bold text-gray-800 mb-4">发布新需求</h2>
           {/* Re-implementing the form for completeness */}
           <div className="space-y-4">
             <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <input className="border p-2 rounded text-sm" placeholder="年级 (如: 高一)" value={newJob.grade} onChange={e => setNewJob({...newJob, grade: e.target.value})} />
                <input className="border p-2 rounded text-sm" placeholder="科目 (如: 数学)" value={newJob.subject} onChange={e => setNewJob({...newJob, subject: e.target.value})} />
             </div>
             <input className="w-full border p-2 rounded text-sm font-medium" placeholder="职位标题 (展示给学生看)" value={newJob.title} onChange={e => setNewJob({...newJob, title: e.target.value})} />
             <div className="grid grid-cols-3 gap-4">
               <select className="border p-2 rounded text-sm bg-white" value={newJob.frequency} onChange={e => setNewJob({...newJob, frequency: parseInt(e.target.value)})}>
                  {[1,2,3,4,5,6,7].map(n => <option key={n} value={n}>每周{n}次</option>)}
               </select>
               <input className="border p-2 rounded text-sm" placeholder="价格 (如: 150)" value={newJob.price} onChange={e => setNewJob({...newJob, price: e.target.value})} />
               <input className="border p-2 rounded text-sm" placeholder="地址 (如: 海淀区)" value={newJob.address} onChange={e => setNewJob({...newJob, address: e.target.value})} />
             </div>
             <div className="grid grid-cols-2 gap-4 bg-gray-50 p-3 rounded">
                <input className="border p-2 rounded text-sm" placeholder="联系人" value={newJob.contact_name} onChange={e => setNewJob({...newJob, contact_name: e.target.value})} />
                <input className="border p-2 rounded text-sm" placeholder="电话 (支付后可见)" value={newJob.contact_phone} onChange={e => setNewJob({...newJob, contact_phone: e.target.value})} />
             </div>
             <button onClick={handleCreateJob} className="w-full bg-black text-white py-3 rounded hover:bg-gray-800 font-bold text-sm">立即发布</button>
           </div>
        </section>
        )}
      </div>
    </div>
  );
};
